### ISSUE TITLE
MathPHP is in need of a Graph component.

### ISSUE THREAD

**Issue by Beakerboy** [graphp/graph#198]
I help out with the MathPHP library (https://github.com/markrogoyski/math-php). Have you heard of it?

Over the years there have been several requests from users about adding a graph theory component. I stumbled across this library and thought that it would be perfect.

Feel free to look over MathPHP and contribute anything you think we need, graph or otherwise. The more developers and more eyes on the code, the better.

If nothing else, I’ll likely be reading through your code for inspiration as a way to independently implement something similar in MathPHP.

**Comment by clue** [comment]
Hey @Beakerboy, thanks for bringing this up here!

I'm indeed aware of MathPHP and think it's a fantastic project! :+1: 

It's my understanding it makes perfect sense to have two independent projects, so I'm not sure there's much to be done here. I think MathPHP is good at what it does and GraPHP is great at what it does. Other than that, I don't so a whole lot of cohesion, because they both deal with different aspects.

If you feel there's anything that either of both projects could benefit from the other, please share and I'm happy to take a look again!

I believe this has been answered, so I'm closing this for now. Please come back with more details if this persists and we can always reopen this :+1:
