### ISSUE TITLE
Whats are supported databases? [question]

### ISSUE THREAD

**Issue by APMU** [graphp/graph#205]
Sorry for my trivial doubt, but:

Whats are supported databases by Graphp?

Where stores or persists the GRAPHs (nodes and edges) or load its from?

Large graphs datasets are supported?

Thanks.

**Comment by sebg1** [comment]
Interesting questions !

**Comment by clue** [comment]
@APMU Excellent question, thanks for bringing this up!

This project implements graph structures (graph, vertices, edges) so that everything can be represented as objects with a simple API to work with in PHP.

This project intentionally does not implement persistence on its own, because this is completely independent of dealing with these objects in memory. There are several options to storing graphs. Personally, I probably would have used the [graphp/graphml](https://github.com/graphp/graphml) library to write to GraphML XML-based files, which have good support in a variety of other tools.

Depending on your particular requirements, you may want to load graph structure from a relational or graph database or really any other database technology or persistence layer. If you're working with a database-centric application, you may not even want to represent these objects in memory at all and may want to run queries within your graph database of choice only. *It all depends*.

I hope this helps :+1:
